---
name: Continous Integration

on: # yamllint disable-line rule:truthy
  push:
  pull_request:
    branches:
      - main

jobs:
  call-workflow-passing-data:
    uses: irishlab-io/pipelines/.github/workflows/reuse.yml@main
