---
name: Continous Integration

on: # yamllint disable-line rule:truthy
  push:
  pull_request:
    branches:
      - main

jobs:
  reuse:
    uses: irishlab-io/pipelines/.github/workflows/reuse.yml@main
  secret:
    uses: irishlab-io/pipelines/.github/workflows/secret.yml@main
    secrets: inherit
  docker-build:
    uses: irishlab-io/pipelines/.github/workflows/docker-build.yml@main
