---
name: Continous Integration

on: # yamllint disable-line rule:truthy
  push:
  pull_request:
    branches:
      - main

jobs:
  reuse:
    uses: irishlab-io/pipelines/generic/reuse.yml@main

  secret:
    uses: irishlab-io/pipelines/generic/secret.yml@main
    needs:
      - reuse
    secrets: inherit

  pre-commit:
    uses: irishlab-io/pipelines/generic/pre-commit.yml@main
    needs:
        - reuse

  docker-build:
    uses: irishlab-io/pipelines/generic/docker-build.yml@main
    needs:
      - reuse
      - secret
