---
name: Continous Integration

on: # yamllint disable-line rule:truthy
  push:
  pull_request:
    branches:
      - main

jobs:
  reuse:
    uses: irishlab-io/pipelines/.github/workflows/reuse.yml@main

  secret:
    uses: irishlab-io/pipelines/.github/workflows/secret.yml@main
    needs:
      - reuse
    secrets: inherit

  pre-commit:
    uses: irishlab-io/pipelines/.github/workflows/pre-commit.yml@main
    needs:
        - reuse

  docker-build:
    uses: irishlab-io/pipelines/.github/workflows/docker-build.yml@main
    needs:
      - pre-commit
      - reuse
      - secret
